sudo: required

language: rust

before_install:
  - sudo apt-get update

cache: cargo

before_cache: |
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin

addons:
  apt:
    packages:
      - libssl-dev

after_success: |
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
